### ISSUE TITLE
Make Report a Problem available in Applications menu?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/feedback#1]
Is there a way to make the Report a Problem functionality available as an application action in the Applications menu? A bit like Check for updates is currently available as an application action from the AppCenter. 
I realize that the About plug isn't really an application which might be a problem.

**Comment by peteruithoven** [comment]
@danrabbit why are you actively hiding this app from the applications menu?
https://github.com/elementary/feedback/commit/012d0113f7fee8641c31b0c541ce96211f6e935b

**Comment by danrabbit** [comment]
@peteruithoven mainly just to have parity with the old dialog, but I'm open to discussion about if it should show as a regular app

**Comment by cassidyjames** [comment]
@danrabbit yeah I think hiding it from Applications Menu makes sense since Switchboard already does show a result for it and as @tintou said, the plug should probably just open the dialog for that result if possible.

In the future if we make the app more of a standalone/full-featured thing I could see revisiting this.

**Comment by hanaral** [comment]
I'd like to point out that the Beta announcement says you can find it by searching in the Applications Menu here:
![Screenshot from 2021-05-01 10-32-12](https://user-images.githubusercontent.com/58219504/116778297-eaf24a00-aa68-11eb-90e3-aaf200594036.png)

But searching either feedback or Feedback returns no results.

**Comment by jeremypw** [comment]
@hanaral  You should get an entry "System -> Send Feedback" when you search the Applications Menu for "feedback".  Is that not the case for you?

**Comment by hanaral** [comment]
@jeremypw Nevermind, yeah it comes up (I was typing in the wrong language lol)
It should be noted though that the icon it uses is the system/firmware icon, I don't think it's very fitting
