### ISSUE TITLE
Swipe to back no longer works on 7.1.0

### ISSUE THREAD

**Issue by ryonakano** [elementary/feedback#100]
### What Happened?

Swipe to right to go back to the previous view no longer possible with 7.1.0

### Steps to Reproduce

Prerequirements:

- Use touchpad with multi-touch support

1. Open Feedback
2. Click "Default apps"
3. Swipe to right to back to Categories view
4. The view won't back, and you need to click the "Categories" button instead:

![Peek 2023-08-23 21-57](https://github.com/elementary/feedback/assets/26003928/f93edbf5-5e93-4c70-b9a4-79de7360edb0)

### Expected Behavior

Swipe to right to go back to the previous view should be possible like 7.0.0:

![Peek 2023-08-23 21-53](https://github.com/elementary/feedback/assets/26003928/ffb00d41-255a-4114-aaf7-63cb7bd3726c)

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
N/A
```

### Hardware Info

- CPU: AMD Ryzen 5 3400G
- RAM: 16 GB
- Graphics: iGPU
- Storage: 490 GB NVMe SSD

**Comment by danirabbit** [comment]
This is due to an upstream issue with Adw/Gtk. It doesn’t sound like we should expect it to be resolved anytime soon unfortunately. Closing as out of scope since it’s an upstream issue
