### ISSUE TITLE
Make apps installable without using the Terminal

### ISSUE THREAD

**Issue by mkniloy** [elementary/feedback#11]
Make apps installable without using the Terminal. Then it will be easier for average computer users to install apps...

**Comment by desiderantes** [comment]
What are you talking about?

**Comment by donadigo** [comment]
Apps can be installed directly from AppCenter not requiring any terminal commands unlike many websites that suggest opening Terminal.

If an app isn't available in AppCenter, there's Eddy and Snaptastic which can install .deb files and snaps. Finally if an app doesn't provide any of these, you have to use Terminal. It's worth to mention that there is also ongoing work for supporting Flatpakref file installation for Flatpak apps.
