### ISSUE TITLE
Report an issue > Switchboard > Online Account - Link is wrong

### ISSUE THREAD

**Issue by Angedestenebres** [elementary/feedback#16]
As said in the title, if you wish to report an issue linked to online account settings, you get this page: 

![Capture d’écran de 2019-10-19 00-34-20](https://user-images.githubusercontent.com/21110485/67132221-3dae3d00-f208-11e9-9373-86f76f4e3e26.png)

The right link is this one: https://github.com/elementary/switchboard-plug-onlineaccounts/issues/new/

**Comment by cassidyjames** [comment]
I don't understand why, but many of the plugs have no word separators in the name. We should double-check the others while we're at it.

**Comment by danrabbit** [comment]
We now get this information from the appdata for each component, so this is fixed as far as Feedback is concerned. If the URL should be something else, then it needs to be changed in online accounts.

But from what I'm seeing here, it looks like this is no longer a 404
