### ISSUE TITLE
Welcome/Onboarding missing

### ISSUE THREAD

**Issue by cassidyjames** [elementary/feedback#44]
## What Happened

I went to file an issue on Onboarding and it's not in Feedback

## Expected Behavior

Onboarding shows under Desktop Components → Welcome

## Steps to Reproduce

1. Open Feedback
2. Click Desktop Components
3. Look for Onboarding/Welcome

## Platform Information

Odin RC

---

We may have intentionally omitted it because it's not clear what "Welcome" means? But in that case I think the solution may be to add a second line from the AppData to make it more clear what each component is, because it's frustrating not being able to send feedback for seemingly random components.

**Comment by danrabbit** [comment]
I think the underlying problem is that we currently have to list all components manually by ID, so it was just never added. I made some progress towards getting components automatically, but haven't been able to finish it
