### ISSUE TITLE
There should be a possibility to give feedback to the Feedback App through the app itself

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/feedback#52]
### Problem

Right now I need to search Github or the elementary repositories themselves to be able to do this.

### Proposal

I don't know if Feedback could be usefully integrated into one of the existing categories.

**Comment by elsiehupp** [comment]
GitHub has [a fairly extensive REST API](https://docs.github.com/en/rest), so it almost certainly could. That said, there would still be a limitation around the fact that opening a GitHub Issue requires a GitHub account, though presumably the Feedback app could use OAuth for that.
