### ISSUE TITLE
The icon view of the components should be more visually consistent

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [elementary/feedback#53]
### Problem

![Screenshot](https://user-images.githubusercontent.com/46536067/144623478-a2315182-eccd-427e-b9ee-e4da8b8eafb7.png)
![Screenshot](https://user-images.githubusercontent.com/46536067/144623659-f7ab3af8-5741-40cf-8d51-d152222bb3ef.png)
![Screenshot](https://user-images.githubusercontent.com/46536067/144623816-104fe193-cb30-4672-9782-471870604ed9.png)
![Screenshot](https://user-images.githubusercontent.com/46536067/144623980-88b39b5c-ab8a-4bdc-a3d4-44d0968ce42e.png)

Right now there are several variants in parallel:

- Text only
- Text with colored icons
- Text with black and white icons

### Proposal

I don't know right now what would be most visually consistent and clear to the user experience system-wide.
My personal feeling at this moment tells me that I am quite comfortable with text & colored icons.

**Comment by lenemter** [comment]
The issue seems to be resolved, text with colored icons is used consistently in OS 7.
