### ISSUE TITLE
Wingpanel missing from report a problem dialog

### ISSUE THREAD

**Issue by peteruithoven** [elementary/feedback#8]
The Wingpanel is missing from report a problem dialog. Should probably be under Desktop Components?

**Comment by danrabbit** [comment]
This is intentional since people tend to report issues for indicators against the panel itself. The same is true of System Settings.

@elementary/ux

**Comment by cassidyjames** [comment]
Hm… yeah I guess it's not super likely they'd have an issue with the panel, and if they filed it against something else, we can always transfer it.

**Comment by danrabbit** [comment]
Yeah, so the next step here is to remove the list of system components and replace it with components marked as "compulsory for desktop" for the currently DE
