### ISSUE TITLE
Feedback app opens on other display

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/feedback#87]
### What Happened?

The feedback app opens on the secondary display

### Steps to Reproduce

I have eOS running on my laptop.
I opened the feedback app when I had not yet attached any external screen.
I attached an external screen and set this external screen as primary display (so that the launcher also is on the bottom of that display).
The laptop display is still enabled as secondary screen.
Both displays output an image.
Then I go to Applications -> Feedback and open it.
The feedback app opens on the laptop screen (old primary screen).

### Expected Behavior

The feedback app should open on the primary screen which in my case was the external screen.
I guess this applies to all apps that store their last window positioning.

I don't know anything related to how the window positioning is saved and restored from a technical point of view.

For me it would make more sense to do the following: 

For each app, independently store the information:
a) Was the screen the primary display at the moment when the app window position was saved? (boolean true/false)
b) If not: save the display number, too.

Then, the next time the app is opened: check the boolean flag. If it is true, open the window on the **current** primary screen (which might have been changed in the meantime)
If the flag is false, try to restore the window on the saved monitor number (which might also be a different physical screen already in the case where the cables of any attached displays were plugged in to a different port etc.).
If there is no screen with the saved number, restore the app to the **current** primary screen.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by lenemter** [comment]
Fixed in https://github.com/elementary/feedback/pull/54.
