### ISSUE TITLE
Remove highlighting over the title

### ISSUE THREAD

**Issue by BenMorant** [elementary/feedback#89]
### Problem

Hello everyone,

When I open Feedback, the title is bigger than the description text (and that's good :) ) but it's also highlighted (with the chosen accent color)

![Captures d'écran de 2023-05-01 10 49 59](https://user-images.githubusercontent.com/52816705/235431164-4b084177-ba9d-410b-808e-cd152b4b21d4.png)

### Proposal

I'm not sure if this highlighting is wanted or not. 
I find it strange I guess, but it's just my personal opinion.
If the highlighting isn't wanted, it should be removed.

**Comment by BenMorant** [comment]
More info : it's no longer highlighted once you click on it

**Comment by BenMorant** [comment]
Even more info : it isn't present in the branch "odin" .
It should be somewhere there : 

`       var primary_label = new Gtk.Label (_("Send feedback for which component?")) {
            hexpand = true,
            selectable = true,
            max_width_chars = 50,
            wrap = true,
            xalign = 0
        };
        primary_label.add_css_class (Granite.STYLE_CLASS_TITLE_LABEL);
`

in src/MainWindow.vala

( the code that was responsible for displaying the same primary label in odin was 

` var primary_label = new Gtk.Label (_("Send feedback for which component?"));
        primary_label.xalign = 0;
        primary_label.get_style_context ().add_class (Granite.STYLE_CLASS_PRIMARY_LABEL);
`

(I know it's barely comparable)
)

I don't succeed to see what is written in Granite.STYLE_CLASS_TITLE_LABEL . Not sure if it's where the issue is.

**Comment by lenemter** [comment]
@BenMorant AFAIK this is an accessibility feature, but the issue here is that the title is focused by default, instead of on demand when you press `Tab`.

This is not present in `odin` branch because `odin` is GTK 3 version of the app, while current `master` is GTK 4 app.

**Comment by BenMorant** [comment]
Yeah, I know that.
Seems that Granite 7's Granite.STYLE_CLASS_TITLE_LABEL does highlight labels with the accent color ( "old" Granite's STYLE_CLASS_PRIMARY_LABEL , which also was/is a Style class for title label text in a Granite.MessageDialog didn't do that)

I don't succeed to see the CSS behind that for now.

I notice that neither granite-demo (https://github.com/elementary/granite) for its  MessageDialog example nor sideload for its main window (https://github.com/elementary/sideload/blob/master/src/MainWindow.vala) use Granite.STYLE_CLASS_TITLE_LABEL

I guess you're right about the "real" issue ( STYLE_CLASS_TITLE_LABEL should be on demand by pressing tab.

I should close this issue and open a new one, more specific, for Granite ?
