### ISSUE TITLE
Web is a terrible browser

### ISSUE THREAD

**Issue by tetsuo29** [elementary/feedback#92]
### What Happened?

eOS is beautiful but, upon initial install it is 110% necessary to install a different web browser than Web. This has to be something that scares people off when they are checking out elementary.

### Steps to Reproduce

1. Install elementary
2. Attempt to use Web
3. Discover that it is slow and doesn't render pages correctly
4. Figure out how to install another browser
5. -OR- Give up on elementary

### Expected Behavior

A distro should use a competent browser (like Firefox, Opera, Chromium) as its default so that the "out of the box" experience for new users is positive.

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by danirabbit** [comment]
Real people with feelings work very hard on this software. Non-constructive feedback is not welcome. 👋
